spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  datasource:
    url: jdbc:postgresql://${db_url}/inventory?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${db_username}
    password: ${db_password}

products:
  images:
    path: product_images/

base:
  front:
    image:
      url: http://localhost:8080/product_images/
