server:
  port: 8082

spring:
  application:
    name: order

  profiles:
    active: dev

  config:
    import: configserver:${config.server.url}

eureka:
  client:
    service-url:
      defaultZone: ${service_discovery_url}
    register-with-eureka: true
    fetch-registry: true
