scrape_configs:
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'inventory-service'
  - job_name: 'aichat-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'aichat-service'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'order-service'