server:
  port: 8084

spring:
  application:
    name: aichat

  profiles:
    active: dev

  config:
    import: configserver:${config.server.url}

eureka:
  client:
    service-url:
      defaultZone: ${service_discovery_url}
    register-with-eureka: true
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: env,conditions,beans,configprops
  endpoint:
    env:
      show-values: ALWAYS