spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  datasource:
    url: jdbc:postgresql://${db_url}/order?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${db_username}
    password: ${db_password}

  ai:
    openai:
      api-key: ${openai_api_key}
      chat:
        options:
          model: gpt-4.1-nano

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            # TODO: use different db for chat memory
            schema: classpath:/schemas/schema-postgresql.sql

    vectorstore:
      qdrant:
        initialize-schema: true
        collection-name: ecom_shaker_collection
        host: ${vectorstore_host}
        port: 6334

logging:
  level:
    org.springframework.http.client: DEBUG
    org.springframework.web.client: DEBUG



